<?php
namespace App\Validators\Product\Category;

use App\Validators\ValidatorAbstract;

/**
 * Created by PhpStorm.
 * User: ivan.li
 * Date: 2/13/2017
 * Time: 11:38 AM
 */
class StoreValidator extends ValidatorAbstract
{
    /**
     * Insert new rule method to validator
     *
     * @param array $data
     * @param bool $throw
     * @return bool|\Illuminate\Support\MessageBag
     */
    public function validate(array $data, $throw = true)
    {
        $this->validator->extendImplicit('unique_per_user', function ($message, $value, $parameters) {
            $currentCategoryNames = auth()->user()->categories->map->category_name->all();
            return !in_array($value, $currentCategoryNames);
        });
        return parent::validate($data, $throw); // TODO: Change the autogenerated stub
    }

    /**
     * Get pre-set validation rules
     *
     * @param null $id
     * @return array
     */
    protected function getRules($id = null)
    {
        return [
            'category_name' => 'required|max:191|unique_per_user'
        ];
    }
}