<template>
    <tr>
        <td>
            {{ report.reportable_type | capitalise }}: {{ reportableName }}
        </td>
        <td>
            {{ frequency | capitalise }}
        </td>
        <td>
            {{ lastReportAt | formatDateTime(datetimeFormat) }}
        </td>
        <td class="text-center">
            <a href="#" class="text-muted" @click.prevent="editReport">
                <i class="glyphicon glyphicon-pencil"></i>
            </a>
        </td>
        <category-report-popup v-if="editingCategoryReport" :current-category="reportable" @edited-report="editedReport" @deleted-report="deletedReport" @cancel-edit="cancelEditReport"></category-report-popup>
        <product-report-popup v-if="editingProductReport" :current-product="reportable" @edited-report="editedReport" @deleted-report="deletedReport" @cancel-edit="cancelEditReport"></product-report-popup>

        <delete-confirmation v-if="deleteParams.active" :deleteParams="deleteParams" @cancelDelete="cancelDelete" @confirmDelete="confirmDelete"></delete-confirmation>
        <loading v-if="isDeletingReport"></loading>
    </tr>
</template>

<script>
    import deleteConfirmation from '../../fragments/modals/DeleteConfirmation.vue';
    import loading from '../../fragments/loading/Loading.vue';

    import categoryReportPopup from '../report/popups/Category.vue';
    import productReportPopup from '../report/popups/Product.vue';

    import capitalise from '../../../filters/capitalise';
    import formatDateTime from '../../../filters/formatDateTime';

    export default {
        components: {
            categoryReportPopup,
            productReportPopup,

            deleteConfirmation,
            loading,
        },
        data(){
            return {
                deleteParams: {
                    title: 'report',
                    list: [
                        'All categories of this report',
                        'All products of this report',
                        'All URLs of this report',
                        'All charts generated by this report',
                        'All reports generated by this report',
                        'Pricing information'
                    ],
                    active: false
                },
                isDeletingReport: false,
                editingCategoryReport: false,
                editingProductReport: false,
            }
        },
        props: [
            'current-report'
        ],
        mounted() {
            console.info('SingleReportRow component is mounted');
        },
        computed: {
            report() {
                return this.currentReport;
            },
            reportable(){
                return this.report.reportable;
            },
            reportableName(){
                switch (this.report.reportable_type) {
                    case 'product':
                        return this.reportable.product_name;
                        break;
                    case 'category':
                        return this.reportable.category_name;
                        break;
                }
                return null;
            },
            frequency(){
                let frequency = "";
                switch (this.report.frequency) {
                    case 'day':
                        frequency = 'daily at ' + this.report.time;
                        break;
                    case 'week':
                        let days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
                        frequency = 'weekly on ' + days[this.report.day];
                        break;
                    case 'month':
                        frequency = 'monthly on ' + this.report.date;
                        break;
                }

                return frequency;
            },
            lastReport(){
                if (this.report.historical_reports.length > 0) {
                    return this.report.historical_reports[this.report.historical_reports.length - 1];
                }
                return null;
            },
            lastReportAt(){
                if (this.lastReport !== null) {
                    return this.lastReport.created_at;
                }
            },
            dateFormat(){
                return user.allPreferences.DATE_FORMAT;
            },
            timeFormat(){
                return user.allPreferences.TIME_FORMAT;
            },
            datetimeFormat(){
                return this.dateFormat + ' ' + this.timeFormat;
            },
        },
        methods: {
            editReport(){
                switch (this.report.reportable_type) {
                    case 'product':
                        this.editingProductReport = true;
                        break;
                    case 'category':
                        this.editingCategoryReport = true;
                        break;
                }
            },
            editedReport(){
                this.cancelEditReport();
                this.emitReloadReports();
            },
            deletedReport(){
                this.cancelEditReport();
                this.emitReloadReports();
            },
            cancelEditReport(){
                this.editingProductReport = false;
                this.editingCategoryReport = false;
            },
            emitReloadReports(){
                this.$emit('reload-reports');
            }
        }
    }
</script>

<style>

</style>