<template>
    <tr>
        <td v-text="user.id"></td>
        <td v-text="user.first_name"></td>
        <td v-text="user.last_name"></td>
        <td v-text="user.email"></td>
        <td class="text-center">
            <a :href="user.urls.show" class="text-muted">
                <i class="glyphicon glyphicon-search"></i>
            </a>
            &nbsp;
            <a :href="user.urls.edit" class="text-muted">
                <i class="glyphicon glyphicon-pencil"></i>
            </a>
            &nbsp;
            <a href="#" class="text-danger" @click.prevent="onClickDeleteUser">
                <i class="glyphicon glyphicon-trash"></i>
            </a>
        </td>
        <delete-confirmation v-if="deleteParams.active" :deleteParams="deleteParams" @cancelDelete="cancelDelete" @confirmDelete="confirmDelete"></delete-confirmation>
        <loading v-if="isDeletingUser"></loading>
    </tr>
</template>

<script>
    import deleteConfirmation from '../../../fragments/modals/DeleteConfirmation.vue';
    import loading from '../../../Loading.vue';

    export default {
        components: {
            deleteConfirmation,
            loading,
        },
        data(){
            return {
                deleteParams: {
                    title: 'user',
                    list: [
                        'All categories of this user',
                        'All products of this user',
                        'All URLs of this user',
                        'All charts generated by this user',
                        'All reports generated by this user',
                        'Pricing information'
                    ],
                    active: false
                },
                isDeletingUser: false,
            }
        },
        props: [
            'current-user'
        ],
        mounted() {
            console.info('SingleUserRow component is mounted');
        },
        computed: {
            user: function () {
                return this.currentUser;
            }
        },
        methods: {
            onClickDeleteUser(){
                this.deleteParams.active = true;
            },
            cancelDelete(){
                this.deleteParams.active = false;
            },
            confirmDelete(){
                this.deleteParams.active = false;
                this.deleteUser()
            },
            deleteUser(){
                this.isDeletingUser = true;
                axios.delete(this.user.urls.delete).then(response=> {
                    this.isDeletingUser = false;
                    if (response.data.status == true) {
                        this.$emit('reloadUsers');
                    }
                }).catch(error=> {
                    this.isDeletingUser = false;
                })
            }
        }
    }
</script>

<style>
</style>