<?php
namespace App\Validators\Product\Site;

use App\Validators\ValidatorAbstract;

/**
 * Created by PhpStorm.
 * User: ivan.li
 * Date: 2/15/2017
 * Time: 11:58 AM
 */
class StoreValidator extends ValidatorAbstract
{

    /**
     * Insert new rule method to validator
     *
     * @param array $data
     * @param bool $throw
     * @return bool|\Illuminate\Support\MessageBag
     */
    public function validate(array $data, $throw = true)
    {
        $this->validator->extendImplicit('unique_per_product', function ($message, $value, $parameters)  use ($data) {
            $builder = auth()->user()->sites();
            if (isset($data['product_id'])) {
                $builder->where('product_id', $data['product_id']);
            }
            $currentSiteURLs = $builder->get()->map->siteUrl->all();
            return !in_array($value, $currentSiteURLs);
        });
        return parent::validate($data, $throw); // TODO: Change the autogenerated stub
    }

    /**
     * Get pre-set validation rules
     *
     * @param null $id
     * @return array
     */
    protected function getRules($id = null)
    {
        return [
            'full_path' => 'required|url|max:2083|unique_per_product'
        ];
    }
}